apiVersion: v1
kind: Service
metadata:
  name: books-service
spec:
  ports:
  - port: 8090
    targetPort: 8090
    nodePort: 30090
    name: http
  selector:
    app:books-service
  type: NodePort
---
apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: books-service
spec:
  selector:
    matchLabels:
      app:  books-service
  replicas: 1 # tells deployment to run 3 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app:  books-service
    spec:
      containers:
      - name:  books-service
        image: anescobar/books-service:latest
        ports:
        - containerPort: 8090
          name: server
